<?
//COMMON
include_once("../lib/common/mysqldb.class.php");
include_once("../lib/control/ctlevento_c.class.php");
include_once("../js/calendar/calendar.php");

//MODEL
include_once("../lib/model/evento_c.class.php");
include_once("../lib/model/municipio.class.php");
include_once("../lib/model/depto.class.php");
include_once("../lib/model/actor.class.php");
include_once("../lib/model/cat_evento_c.class.php");
include_once("../lib/model/subcat_evento_c.class.php");
include_once("../lib/model/fuente_evento_c.class.php");
include_once("../lib/model/subfuente_evento_c.class.php");
include_once("../lib/model/edad.class.php");
include_once("../lib/model/rango_edad.class.php");
include_once("../lib/model/sexo.class.php");
include_once("../lib/model/condicion_mina.class.php");
include_once("../lib/model/subcondicion.class.php");
include_once("../lib/model/estado_mina.class.php");
include_once("../lib/model/etnia.class.php");
include_once("../lib/model/subetnia.class.php");
include_once("../lib/model/ocupacion.class.php");

//DAO
include_once("../lib/dao/evento_c.class.php");
include_once("../lib/dao/municipio.class.php");
include_once("../lib/dao/depto.class.php");
include_once("../lib/dao/actor.class.php");
include_once("../lib/dao/cat_evento_c.class.php");
include_once("../lib/dao/subcat_evento_c.class.php");
include_once("../lib/dao/fuente_evento_c.class.php");
include_once("../lib/dao/subfuente_evento_c.class.php");
include_once("../lib/dao/edad.class.php");
include_once("../lib/dao/rango_edad.class.php");
include_once("../lib/dao/sexo.class.php");
include_once("../lib/dao/condicion_mina.class.php");
include_once("../lib/dao/subcondicion.class.php");
include_once("../lib/dao/estado_mina.class.php");
include_once("../lib/dao/etnia.class.php");
include_once("../lib/dao/subetnia.class.php");
include_once("../lib/dao/ocupacion.class.php");

?>