<?
//COMMON
include_once("lib/common/mysqldb.class.php");

//MODEL
include_once("lib/model/evento.class.php");
include_once("lib/model/municipio.class.php");
include_once("lib/model/depto.class.php");
include_once("lib/model/region.class.php");
include_once("lib/model/poblado.class.php");
include_once("lib/model/resguardo.class.php");
include_once("lib/model/parque_nat.class.php");
include_once("lib/model/div_afro.class.php");
include_once("lib/model/tipo_evento.class.php");
include_once("lib/model/cat_tipo_evento.class.php");
include_once("lib/model/actor.class.php");
include_once("lib/model/cons_hum.class.php");
include_once("lib/model/riesgo_hum.class.php");
include_once("lib/model/proyecto.class.php");
include_once("lib/model/moneda.class.php");
include_once("lib/model/estado_proyecto.class.php");
include_once("lib/model/contacto.class.php");
include_once("lib/model/tipo_vinculorgpro.class.php");
include_once("lib/model/org.class.php");
include_once("lib/model/sector.class.php");
include_once("lib/model/poblacion.class.php");
include_once("lib/model/tema.class.php");
include_once("lib/model/tipo_org.class.php");
include_once("lib/model/enfoque.class.php");
include_once("lib/model/dato_sectorial.class.php");
include_once("lib/model/cat_d_s.class.php");
include_once("lib/model/u_d_s.class.php");
include_once("lib/model/clase_desplazamiento.class.php");
include_once("lib/model/tipo_desplazamiento.class.php");
include_once("lib/model/fuente.class.php");
include_once("lib/model/periodo.class.php");
include_once("lib/model/desplazamiento.class.php");

//DAO
include_once("lib/dao/evento.class.php");
include_once("lib/dao/municipio.class.php");
include_once("lib/dao/depto.class.php");
include_once("lib/dao/region.class.php");
include_once("lib/dao/poblado.class.php");
include_once("lib/dao/resguardo.class.php");
include_once("lib/dao/parque_nat.class.php");
include_once("lib/dao/div_afro.class.php");
include_once("lib/dao/tipo_evento.class.php");
include_once("lib/dao/cat_tipo_evento.class.php");
include_once("lib/dao/actor.class.php");
include_once("lib/dao/cons_hum.class.php");
include_once("lib/dao/riesgo_hum.class.php");
include_once("lib/dao/proyecto.class.php");
include_once("lib/dao/moneda.class.php");
include_once("lib/dao/estado_proyecto.class.php");
include_once("lib/dao/contacto.class.php");
include_once("lib/dao/tipo_vinculorgpro.class.php");
include_once("lib/dao/org.class.php");
include_once("lib/dao/sector.class.php");
include_once("lib/dao/poblacion.class.php");
include_once("lib/dao/tema.class.php");
include_once("lib/dao/tipo_org.class.php");
include_once("lib/dao/enfoque.class.php");
include_once("lib/dao/dato_sectorial.class.php");
include_once("lib/dao/cat_d_s.class.php");
include_once("lib/dao/u_d_s.class.php");
include_once("lib/dao/clase_desplazamiento.class.php");
include_once("lib/dao/tipo_desplazamiento.class.php");
include_once("lib/dao/fuente.class.php");
include_once("lib/dao/periodo.class.php");
include_once("lib/dao/desplazamiento.class.php");

?>